[package]
name = "fulu"
version = "0.1.0"
edition = "2021"
description = "The code generator for Bagua"
repository = "https://github.com/liuzsen/bagua"
license = "Apache-2.0"
authors = ["liuzsen"]

[dependencies]
